[2025-03-22T10:40:53.827+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T10:40:53.833+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_dag.train_model manual__2025-03-22T05:40:50.541436+00:00 [queued]>
[2025-03-22T10:40:53.846+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_dag.train_model manual__2025-03-22T05:40:50.541436+00:00 [queued]>
[2025-03-22T10:40:53.846+0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-22T10:40:53.860+0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): train_model> on 2025-03-22 05:40:50.541436+00:00
[2025-03-22T10:40:53.863+0500] {standard_task_runner.py:72} INFO - Started process 40040 to run task
[2025-03-22T10:40:53.866+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'train_dag', 'train_model', 'manual__2025-03-22T05:40:50.541436+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmprxodi6cw']
[2025-03-22T10:40:53.867+0500] {standard_task_runner.py:105} INFO - Job 9: Subtask train_model
[2025-03-22T10:40:53.892+0500] {task_command.py:467} INFO - Running <TaskInstance: train_dag.train_model manual__2025-03-22T05:40:50.541436+00:00 [running]> on host DESKTOP-LSRPTF5.
[2025-03-22T10:40:53.930+0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_dag' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T05:40:50.541436+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-22T05:40:50.541436+00:00'
[2025-03-22T10:40:53.931+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-22T10:40:53.931+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-22T10:40:53.931+0500] {logging_mixin.py:190} INFO - Current task name:train_model state:running start_date:2025-03-22 05:40:53.833810+00:00
[2025-03-22T10:40:53.931+0500] {logging_mixin.py:190} INFO - Dag name:train_dag and current dag run status:running
[2025-03-22T10:40:53.931+0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T10:40:54.153+0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ruslan/metro/airflow/dags/main.py", line 39, in train_model
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=111)
NameError: name 'train_test_split' is not defined
[2025-03-22T10:40:54.156+0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-22T10:40:54.156+0500] {logging_mixin.py:190} INFO - Task start:2025-03-22 05:40:53.833810+00:00 end:2025-03-22 05:40:54.155867+00:00 duration:0.322057
[2025-03-22T10:40:54.156+0500] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): train_model> dag:<DAG: train_dag> dagrun:<DagRun train_dag @ 2025-03-22 05:40:50.541436+00:00: manual__2025-03-22T05:40:50.541436+00:00, state:running, queued_at: 2025-03-22 05:40:50.548733+00:00. externally triggered: True>
[2025-03-22T10:40:54.156+0500] {logging_mixin.py:190} INFO - Failure caused by name 'train_test_split' is not defined
[2025-03-22T10:40:54.156+0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=train_dag, task_id=train_model, run_id=manual__2025-03-22T05:40:50.541436+00:00, execution_date=20250322T054050, start_date=20250322T054053, end_date=20250322T054054
[2025-03-22T10:40:54.173+0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T10:40:54.174+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task train_model (name 'train_test_split' is not defined; 40040)
Traceback (most recent call last):
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ruslan/metro/airflow/dags/main.py", line 39, in train_model
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=111)
NameError: name 'train_test_split' is not defined
[2025-03-22T10:40:54.199+0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-22T10:40:54.207+0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-22T10:40:54.207+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
